version: "3.9"
services:
  api:
    container_name: api
    build: ./src/api
    ports:
      - "5000:5000"
    volumes: ['./src/api:/api']
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    links:
      - "db:db"
  db:
    container_name: db
    build: ./src/db
    ports:
      - "5432:5432"
#  dash:
#    container_name: dash
#    build: ./src/dash
#    depends_on:
#      - api
#    ports:
#      - "4000:4000"
#    volumes: ['./src/dash:/dash']
#    environment:
#      - PYTHONUNBUFFERED=1
  pgadmin:
    container_name: pg_admin
    build: ./src/pgadmin
    ports:
    - "8080:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"
  react:
    container_name: react
    build: ./src/frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes: ['./src/frontend/src:/frontend/src']
    ports:
      - "3000:3000"

volumes:
  db-data:
  pgadmin-data:
