FROM python:3.9

COPY . /api
WORKDIR /api

ENV FLASK_APP=./app.py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apt-get update && apt-get install -y --no-install-recommends \
  gcc \
  musl-dev \
  libpq-dev \
  postgresql-client \
  && rm -rf /var/lib/apt/lists/*
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install --no-cache-dir gunicorn
EXPOSE 5000
CMD gunicorn --bind 0.0.0.0:5000 wsgi:app --timeout 0 --workers 16