export interface AisTrack{
    id: number,
    mmsi: number,
    begin_ts: Date,
    end_ts: Date,
    destination: string,
    cargo_type: string, 
    eta: Date, 
    imo: string, 
    mobile_type: string, 
    callsign: string, 
    name: string, 
    ship_type: string, 
    width: number, 
    length: number,
    draught: number, 
    a: number, 
    b: number, 
    c: number, 
    d: number,
    coordinates: [number, number][]
}
