name: Deploy code base

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy code base
    runs-on: ubuntu-latest
    steps:
      - name: DeployWithSsh
        uses: appleboy/ssh-action@master
        with:
          host: techsource.dk
          username: ais
          key: ${{ secrets.ais_pkey }}
          port: 22
          script: |
            cd /home/ais/sw618f21/
            git checkout ${GITHUB_REF##*/}
            git pull
            docker-compose -f docker-compose.prod.yml build
            docker-compose -f docker-compose.prod.yml up